version: '3'
services:
  web:
    env_file: ./.env
    build: ./nginx
    environment: 
      NGINX_VERSION: ${NGINX_VERSION}
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    links:
      - php71
      - php53
      - mysql
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - './code:/code:cached'
      - './nginx/sites:/etc/nginx/conf.d/'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
  mysql:
    env_file: ./.env
    build: ./mysql
    volumes:
      - './db_data:/var/lib/mysql'
      - './shared:/shared'
    container_name: mysql
    restart: always
    environment: 
      MYSQL_VERSION: ${MYSQL_VERSION}
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  php71:
    env_file: ./.env
    build: ./php/php71
    environment:
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    links:
      - mysql
    expose:
      - '9002'
    volumes:
      - './code:/code:cached'
      - './php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './php/php71/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './php/php71/ext:/usr/local/etc/php/conf.d'
      - './php/php71/php.ini:/usr/local/etc/php/php.ini'
    working_dir: /code
  php53:
    env_file: ./.env
    build: ./php/php53
    environment:
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    links:
      - mysql
    expose:
      - '9003'
    volumes:
      - './code:/code:cached'
      - './php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './php/php53/ext:/usr/local/etc/php/conf.d'
      - './php/php53/php.ini:/usr/local/etc/php/php.ini'
    working_dir: /code