version: '2.2'
services:
  web:
    build: ./nginx
    links:
      - php71
      - php53
      - mysql
    ports:
      - '80:80'
    volumes:
      - './code:/code:cached'
      - './nginx/sites:/etc/nginx/conf.d/'
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './conf/hosts:/etc/hosts'
      - './shared:/shared'
  # mongodb:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   environment:
  #     - MONGO_DATA_DIR=/data/db
  #     - MONGO_LOG_DIR=/var/log/mongodb
  #   volumes:
  #     - ./mongo_data:/data/db
  #     - ./logs/mongodb:/var/log/mongodb
  #   ports:
  #       - 27017:27017
  #   command: mongod --smallfiles --logpath=/dev/null --bind_ip_all # --quiet
  mysql:
    build: ./mysql
    volumes:
      - './db_data:/var/lib/mysql'
      - './shared:/shared'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
  php71:
    build: ./php/php71
    links:
      - mysql
    expose:
      - '9002'
    volumes:
      - './php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './php/php71/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './code:/code:cached'
      - './php/php71/ext:/usr/local/etc/php/conf.d'
      - './php/php71/php.ini:/usr/local/etc/php/php.ini'
      - './conf/hosts:/etc/hosts'
      - './shared:/shared'
    working_dir: /code
  php53:
    build: ./php/php53
    links:
      - mysql
    expose:
      - '9003'
    volumes:
      - './code:/code:cached'
      - './php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './php/php53/ext:/usr/local/etc/php/conf.d'
      - './php/php53/php.ini:/usr/local/etc/php/php.ini'
      - './conf/hosts:/etc/hosts'
      - './shared:/shared'
    working_dir: /code

volumes:
  var: null

networks:
  base: