version: '3'
services:
  web:
    env_file: ./.env
    build: 
      context: ./configuration/nginx
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    environment: 
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    links:
      - php7
      - php53
      - mysql
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - './code:/code:cached'
      - "${NGINX_VHOST_DIR}:/etc/nginx/conf.d/"
      - './configuration/nginx/nginx.conf:/etc/nginx/nginx.conf'
  mysql:
    env_file: ./.env
    build: 
      dockerfile: Dockerfile
      context: ./configuration/mysql
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    volumes:
      - './db_data:/var/lib/mysql'
      - './shared:/shared'
    container_name: mysql
    restart: always
    environment: 
      MYSQL_VERSION: ${MYSQL_VERSION}
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
  php7:
    env_file: ./.env
    build: 
      context: ./configuration/php/php7
      dockerfile: Dockerfile
      args: 
        PHP7_VERSION: ${PHP7_VERSION}
    environment:
      HOST_USER_UID: ${HOST_USER_UID}
      HOST_USER_GID: ${HOST_USER_GID}
    links:
      - mysql
    expose:
      - '9002'
    volumes:
      - './code:/code:cached'
      - './configuration/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
      - './configuration/php/php7/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './configuration/php/php7/ext:/usr/local/etc/php/conf.d'
      - './configuration/php/php7/php.ini:/usr/local/etc/php/php.ini'
    working_dir: /code
